package com.service;

import java.io.*;
import java.net.*;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;

import java.sql.Statement;
import java.util.Properties;
import javax.sql.DataSource;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.dbcp2.BasicDataSourceFactory;

import javax.jws.WebMethod;  
import javax.jws.WebParam;  
import javax.jws.WebResult;  
import javax.jws.WebService; 
//Generated by MyEclipse
@WebService
public interface Ilinda {
	
	public String example(String message);
	public String getversion1();
	
	@WebMethod  
    @WebResult(name="resultMsg") 
	public int cardDeviceRegister(
			@WebParam(name="workStationIP")String workStationIP,    /*终端IP*/
			@WebParam(name="workStationPort")int workStationPort,   /*终端Port*/
			@WebParam(name="encryptIP")String encryptIP,		/*加密机IP*/
			@WebParam(name="encryptPort")int encryptPort,		/*加密机Port*/
			@WebParam(name="cardDeviceName")String cardDeviceName,	/*打印机名称*/
			@WebParam(name="encryptIndex")String encryptIndex,	/*加密因子*/
			@WebParam(name="isDecrypt")boolean isDecrypt);		/*是否加密机制卡*/
	
}